[[redirects]]
  from = "/api/*"
  to = "https://conect2.netlify.app/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://conect2.netlify.app" }

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://conect2.netlify.app"
