# netlify.toml

[[redirects]]
  from = "/api/*"
  to = "https://conect2.netlify.app/:splat"  # Actualiza la URL a HTTPS
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://conect2.netlify.app" }  # Actualiza la URL a HTTPS

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://conect2.netlify.app"  # Actualiza la URL a HTTPS
