# netlify.toml

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
