[[redirects]]
  from = "/api/*"
  to = "https://conect2.netlify.app/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://conect2.netlify.app/user-profile" }

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
      Access-Control-Allow-Credentials = "true"

[build]
  functions = "E:/conecta2/probar2/Conecta2apps/functions"

